<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Product;
use App\Models\ProductInventory;
use App\Models\Tag;

class ProductTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Tag::factory()->count(10)->create();
        $this->command->info('Tags seeded.');
        $randomTagIDs = Tag::all()->random()->limit(2)->pluck('id');

        // Ambil satu user sebagai owner produk
        $user = User::first();

        // Membuat produk dengan data yang telah ditentukan (tanpa loop)
        $products = [
            [
                'sku' => 'OLI-001',
                'name' => '2T Enviro 20W (0,8 Liter)',
                'slug' => '2t-enviro-20w-(0,8liter)',
                'price' => 59000,
                'sale_price' => 59000,
                'status' => Product::ACTIVE,
                'stock_status' => Product::STATUS_IN_STOCK,
                'manage_stock' => true,
                'publish_date' => now(),
                'excerpt' => 'ENVIRO 2T SAE 20 merupakan pelumas kendaraan dua langkah dengan bahan bakar bensin.',
                'body' => 'ENVIRO 2T SAE 20 merupakan pelumas kendaraan dua langkah dengan bahan bakar bensin.',
                'featured_image' => 'images/2T-Enviro.jpg',
            ],
            [
                'sku' => 'OLI-002',
                'name' => 'Enduro 4T 20W-50 (0,8 Liter)',
                'slug' => 'enduro-4t-20w-50-(0,8liter)',
                'price' => 58000,
                'sale_price' => 58000,
                'status' => Product::ACTIVE,
                'stock_status' => Product::STATUS_IN_STOCK,
                'manage_stock' => true,
                'publish_date' => now(),
                'excerpt' => 'ENDURO 4T SAE 20W-50 direkomendasikan untuk motor empat langkah merek Honda,Suzuki,Kawasaki,Yamaha,dan lainya.',
                'body' => 'ENDURO 4T SAE 20W-50 direkomendasikan untuk motor empat langkah merek Honda,Suzuki,Kawasaki,Yamaha,dan lainya.',
                'featured_image' => 'images/Enduro 4T.jpg',
            ],
            [
                'sku' => 'OLI-003',
                'name' => 'Enduro Matic 20W-50 (0,8 Liter)',
                'slug' => 'enduro-matic-20W-50-(0,8liter)',
                'price' => 59000,
                'sale_price' => 59000,
                'status' => Product::ACTIVE,
                'stock_status' => Product::STATUS_IN_STOCK,
                'manage_stock' => true,
                'publish_date' => now(),
                'excerpt' => 'Oli Pertamina Enduro Matic 20W-50 adalah pelumas mesin yang dirancang khusus untuk motor matic.',
                'body' => 'Oli Pertamina Enduro Matic 20W-50 adalah pelumas mesin yang dirancang khusus untuk motor matic.',
                'featured_image' => 'images/Enduro Gear Matic.jpg',
            ],
            [
                'sku' => 'OLI-004',
                'name' => 'Enduro Racing 10W-40 (1 Liter)',
                'slug' => 'enduro-racing-10W-40-(1liter)',
                'price' => 73000,
                'sale_price' => 73000,
                'status' => Product::ACTIVE,
                'stock_status' => Product::STATUS_IN_STOCK,
                'manage_stock' => true,
                'publish_date' => now(),
                'excerpt' => 'Enduro Racing 10W-40 adalah pelumas motor empat langkah.',
                'body' => 'Enduro Racing 10W-40 adalah pelumas motor empat langkah.',
                'featured_image' => 'images/Enduro Racing.jpg',
            ],
            [
                'sku' => 'OLI-005',
                'name' => 'Enduro Matic G (0,8 Liter)',
                'slug' => 'enduro-matic-g-(0,8liter)',
                'price' => 52000,
                'sale_price' => 52000,
                'status' => Product::ACTIVE,
                'stock_status' => Product::STATUS_IN_STOCK,
                'manage_stock' => true,
                'publish_date' => now(),
                'excerpt' => 'Enduro Matic G adalah oli motor matik dirancang khusus untuk mesin motor otomatis.',
                'body' => 'Enduro Matic adalah oli motor matik dirancang khusus untuk mesin motor otomatis.',
                'featured_image' => 'images/Enduro Matic-G.jpg',
            ],
            [
                'sku' => 'OLI-006',
                'name' => 'Fastron Gold 5W-30 (4 Liter)',
                'slug' => 'fastron-gold-5w-30-(4liter)',
                'price' => 52000,
                'sale_price' => 52000,
                'status' => Product::ACTIVE,
                'stock_status' => Product::STATUS_IN_STOCK,
                'manage_stock' => true,
                'publish_date' => now(),
                'excerpt' => 'Enduro Matic G adalah oli motor matik dirancang khusus untuk mesin motor otomatis.',
                'body' => 'Enduro Matic adalah oli motor matik dirancang khusus untuk mesin motor otomatis.',
                'featured_image' => 'images/Fastron Gold.jpg',
            ],
            [
                'sku' => 'OLI-007',
                'name' => 'Fastron Gold 5W-30 (1 Liter)',
                'slug' => 'fastron-gold-5w-30-(1liter)',
                'price' => 615000,
                'sale_price' => 615000,
                'status' => Product::ACTIVE,
                'stock_status' => Product::STATUS_IN_STOCK,
                'manage_stock' => true,
                'publish_date' => now(),
                'excerpt' => 'Fastron Gold 5W-30 direkomendasikan untuk kendaraan generasi terbaru dari pabrikan kendaraan terkemuka.',
                'body' => 'Fastron Gold 5W-30 direkomendasikan untuk kendaraan generasi terbaru dari pabrikan kendaraan terkemuka.',
                'featured_image' => 'images/Fastron Gold.jpg',
            ],
            [
                'sku' => 'OLI-008',
                'name' => 'Fastron Techno 10W-40 (4 Liter)',
                'slug' => 'fastron-techno-10w-40-(4liter)',
                'price' => 90000,
                'sale_price' => 90000,
                'status' => Product::ACTIVE,
                'stock_status' => Product::STATUS_IN_STOCK,
                'manage_stock' => true,
                'publish_date' => now(),
                'excerpt' => '',
                'body' => '',
                'featured_image' => 'images/Fastron Techno 4L.jpg',
            ],
            [
                'sku' => 'OLI-009',
                'name' => 'Fastron Techno 10W-40 (Ungu) 1 Liter',
                'slug' => 'fastron-techno-10w-40-(ungu)-1liter',
                'price' => 73000,
                'sale_price' => 73000,
                'status' => Product::ACTIVE,
                'stock_status' => Product::STATUS_IN_STOCK,
                'manage_stock' => true,
                'publish_date' => now(),
                'excerpt' => '',
                'body' => '',
                'featured_image' => 'images/Fastron Techno 1L.jpg',
            ],
            [
                'sku' => 'OLI-010',
                'name' => 'Meditran S40 (1 Liter)',
                'slug' => 'meditran-s40-(1liter)',
                'price' => 54000,
                'sale_price' => 54000,
                'status' => Product::ACTIVE,
                'stock_status' => Product::STATUS_IN_STOCK,
                'manage_stock' => true,
                'publish_date' => now(),
                'excerpt' => '',
                'body' => '',
                'featured_image' => 'images/Meditran S40 1L.jpg',
            ],
            [
                'sku' => 'OLI-011',
                'name' => 'Meditran S40 (5 Liter)',
                'slug' => 'meditran-s40-(5liter)',
                'price' => 240000,
                'sale_price' => 240000,
                'status' => Product::ACTIVE,
                'stock_status' => Product::STATUS_IN_STOCK,
                'manage_stock' => true,
                'publish_date' => now(),
                'excerpt' => '',
                'body' => '',
                'featured_image' => 'images/Meditran S40 5L.jpg',
            ],
            [
                'sku' => 'OLI-012',
                'name' => 'Meditran S40 (10 Liter)',
                'slug' => 'meditran-s40-(10liter)',
                'price' => 475000,
                'sale_price' => 475000,
                'status' => Product::ACTIVE,
                'stock_status' => Product::STATUS_IN_STOCK,
                'manage_stock' => true,
                'publish_date' => now(),
                'excerpt' => '',
                'body' => '',
                'featured_image' => 'images/Meditran S40 10L.jpg',
            ],
            [
                'sku' => 'OLI-013',
                'name' => 'Meditran SC 15W-40 (1 Liter)',
                'slug' => 'meditran-sc-15w-40-(1liter)',
                'price' => 58000,
                'sale_price' => 58000,
                'status' => Product::ACTIVE,
                'stock_status' => Product::STATUS_IN_STOCK,
                'manage_stock' => true,
                'publish_date' => now(),
                'excerpt' => '',
                'body' => '',
                'featured_image' => 'images/Meditran SC 15W-40.jpg',
            ],
            [
                'sku' => 'OLI-014',
                'name' => 'Meditran SX 15W-40 (1 Liter)',
                'slug' => 'meditran-sx-15w-40-(1liter)',
                'price' => 62000,
                'sale_price' => 62000,
                'status' => Product::ACTIVE,
                'stock_status' => Product::STATUS_IN_STOCK,
                'manage_stock' => true,
                'publish_date' => now(),
                'excerpt' => '',
                'body' => '',
                'featured_image' => 'images/Meditran SX 15W-40 1L.jpg',
            ],
            [
                'sku' => 'OLI-015',
                'name' => 'Meditran SX 15W-40 (4 Liter)',
                'slug' => 'meditran-sx-15w-40-(4liter)',
                'price' => 225000,
                'sale_price' => 225000,
                'status' => Product::ACTIVE,
                'stock_status' => Product::STATUS_IN_STOCK,
                'manage_stock' => true,
                'publish_date' => now(),
                'excerpt' => '',
                'body' => '',
                'featured_image' => 'images/Meditran SX 15W-40 4L.jpg',
            ],
            [
                'sku' => 'OLI-016',
                'name' => 'Meditran SX 15W-40 (10 Liter)',
                'slug' => 'meditran-sx-15w-40-(10liter)',
                'price' => 550000,
                'sale_price' => 550000,
                'status' => Product::ACTIVE,
                'stock_status' => Product::STATUS_IN_STOCK,
                'manage_stock' => true,
                'publish_date' => now(),
                'excerpt' => '',
                'body' => '',
                'featured_image' => 'images/Meditran SX 15W-40 10L.jpg',
            ],
            [
                'sku' => 'OLI-017',
                'name' => 'Mesran B40 (1 Liter)',
                'slug' => 'mesran-b40-(1liter)',
                'price' => 52000,
                'sale_price' => 52000,
                'status' => Product::ACTIVE,
                'stock_status' => Product::STATUS_IN_STOCK,
                'manage_stock' => true,
                'publish_date' => now(),
                'excerpt' => '',
                'body' => '',
                'featured_image' => 'images/Mesran B40 1L.jpg',
            ],
            [
                'sku' => 'OLI-018',
                'name' => 'Mesran B40 (4 Liter)',
                'slug' => 'mesran-b40-(4liter)',
                'price' => 195000,
                'sale_price' => 195000,
                'status' => Product::ACTIVE,
                'stock_status' => Product::STATUS_IN_STOCK,
                'manage_stock' => true,
                'publish_date' => now(),
                'excerpt' => '',
                'body' => '',
                'featured_image' => 'images/Mesran B40 4L.jpg',
            ],
            [
                'sku' => 'OLI-019',
                'name' => 'Mesran B40 (5 Liter)',
                'slug' => 'mesran-b40-(5liter)',
                'price' => 195000,
                'sale_price' => 195000,
                'status' => Product::ACTIVE,
                'stock_status' => Product::STATUS_IN_STOCK,
                'manage_stock' => true,
                'publish_date' => now(),
                'excerpt' => '',
                'body' => '',
                'featured_image' => 'images/Mesran B40 5L.jpg',
            ],
            [
                'sku' => 'OLI-020',
                'name' => 'Mesran B40 (10 Liter)',
                'slug' => 'mesran-b40-(10liter)',
                'price' => 460000,
                'sale_price' => 460000,
                'status' => Product::ACTIVE,
                'stock_status' => Product::STATUS_IN_STOCK,
                'manage_stock' => true,
                'publish_date' => now(),
                'excerpt' => '',
                'body' => '',
                'featured_image' => 'images/Mesran B40 10L.jpg',
            ],
            [
                'sku' => 'OLI-021',
                'name' => 'Mesran Super 20W-50 (0,8 Liter)',
                'slug' => 'mesran-super-20w-(0,8liter)',
                'price' => 48000,
                'sale_price' => 48000,
                'status' => Product::ACTIVE,
                'stock_status' => Product::STATUS_IN_STOCK,
                'manage_stock' => true,
                'publish_date' => now(),
                'excerpt' => '',
                'body' => '',
                'featured_image' => 'images/Mesran Super 20W-50 0.8L.jpg',
            ],
            [
                'sku' => 'OLI-022',
                'name' => 'Mesran Super 20W-50 (1 Liter)',
                'slug' => 'mesran-super-20w-(1liter)',
                'price' => 53000,
                'sale_price' => 53000,
                'status' => Product::ACTIVE,
                'stock_status' => Product::STATUS_IN_STOCK,
                'manage_stock' => true,
                'publish_date' => now(),
                'excerpt' => '',
                'body' => '',
                'featured_image' => 'images/Mesran Super 20W-50 1L.jpg',
            ],
            [
                'sku' => 'OLI-023',
                'name' => 'Mesran Super 20W-50 (4 Liter)',
                'slug' => 'mesran-super-20w-(4liter)',
                'price' => 200000,
                'sale_price' => 200000,
                'status' => Product::ACTIVE,
                'stock_status' => Product::STATUS_IN_STOCK,
                'manage_stock' => true,
                'publish_date' => now(),
                'excerpt' => '',
                'body' => '',
                'featured_image' => 'images/Mesran Super 20W-50 4L.jpg',
            ],
            [
                'sku' => 'OLI-024',
                'name' => 'Mesrania 2T Super 20W (1 Liter)',
                'slug' => 'mesrania-2t-super-20w-(1liter)',
                'price' => 55000,
                'sale_price' => 55000,
                'status' => Product::ACTIVE,
                'stock_status' => Product::STATUS_IN_STOCK,
                'manage_stock' => true,
                'publish_date' => now(),
                'excerpt' => '',
                'body' => '',
                'featured_image' => 'images/Mesrania 2T Super 20W 1L.jpg',
            ],
            [
                'sku' => 'OLI-025',
                'name' => 'Prima XP 20W-50 (1 Liter)',
                'slug' => 'prima-xp-20w-50-(1-liter)',
                'price' => 56000,
                'sale_price' => 56000,
                'status' => Product::ACTIVE,
                'stock_status' => Product::STATUS_IN_STOCK,
                'manage_stock' => true,
                'publish_date' => now(),
                'excerpt' => '',
                'body' => '',
                'featured_image' => 'images/Prima XP 20W-50 1L.jpg',
            ],
            [
                'sku' => 'OLI-026',
                'name' => 'Prima XP 20W-50 (4 Liter)',
                'slug' => 'prima-xp-20w-50-(4-liter)',
                'price' => 202000,
                'sale_price' => 202000,
                'status' => Product::ACTIVE,
                'stock_status' => Product::STATUS_IN_STOCK,
                'manage_stock' => true,
                'publish_date' => now(),
                'excerpt' => '',
                'body' => '',
                'featured_image' => 'images/Prima XP 20W-50 4L.jpg',
            ],
            [
                'sku' => 'OLI-027',
                'name' => 'Prima Synthetic 10W-40 (1 Liter)',
                'slug' => 'prima-synthetic-10w-40(1-liter)',
                'price' => 75000,
                'sale_price' => 75000,
                'status' => Product::ACTIVE,
                'stock_status' => Product::STATUS_IN_STOCK,
                'manage_stock' => true,
                'publish_date' => now(),
                'excerpt' => '',
                'body' => '',
                'featured_image' => 'images/Prima XP Synthetic 10W-40 1L.jpg',
            ],
            [
                'sku' => 'OLI-028',
                'name' => 'Prima Synthetic 10W-40 (4 Liter)',
                'slug' => 'prima-synthetic-10w-40(4-liter)',
                'price' => 280000,
                'sale_price' => 280000,
                'status' => Product::ACTIVE,
                'stock_status' => Product::STATUS_IN_STOCK,
                'manage_stock' => true,
                'publish_date' => now(),
                'excerpt' => '',
                'body' => '',
                'featured_image' => 'images/Prima XP Synthetic 10W-40 4L.jpg',
            ],
            [
                'sku' => 'OLI-029',
                'name' => 'Enduro Gear Matic (0,12 Liter)',
                'slug' => 'enduro-gear-matic-(0,12-liter)',
                'price' => 18000,
                'sale_price' => 18000,
                'status' => Product::ACTIVE,
                'stock_status' => Product::STATUS_IN_STOCK,
                'manage_stock' => true,
                'publish_date' => now(),
                'excerpt' => '',
                'body' => '',
                'featured_image' => 'images/Enduro Gear Matic.jpg',
            ],
            [
                'sku' => 'OLI-030',
                'name' => ' Fastron Eco Green 0W-20 (3,5 Liter)',
                'slug' => 'fastron-eco-green-0w-20-(3,5-liter)',
                'price' => 18000,
                'sale_price' => 18000,
                'status' => Product::ACTIVE,
                'stock_status' => Product::STATUS_IN_STOCK,
                'manage_stock' => true,
                'publish_date' => now(),
                'excerpt' => '',
                'body' => '',
                'featured_image' => 'images/Fastron Eco Green 0W-20.jpg',
            ],
            [
                'sku' => 'OLI-031',
                'name' => ' Fastron Eco Green 5W-30 (3,5 Liter)',
                'slug' => 'fastron-eco-green-5w-30-(3,5-liter)',
                'price' => 275000,
                'sale_price' => 275000,
                'status' => Product::ACTIVE,
                'stock_status' => Product::STATUS_IN_STOCK,
                'manage_stock' => true,
                'publish_date' => now(),
                'excerpt' => '',
                'body' => '',
                'featured_image' => 'images/Fastron Eco Green 5W-30.jpg',
            ],
            [
                'sku' => 'OLI-032',
                'name' => ' Enduro Matic V (1 Liter)',
                'slug' => 'enduro-matic-v-(1-liter)',
                'price' => 67000,
                'sale_price' => 67000,
                'status' => Product::ACTIVE,
                'stock_status' => Product::STATUS_IN_STOCK,
                'manage_stock' => true,
                'publish_date' => now(),
                'excerpt' => '',
                'body' => '',
                'featured_image' => 'images/Enduro Matic V.jpg',
            ],
            [
                'sku' => 'OLI-033',
                'name' => ' Enduro Matic S (0,8 Liter)',
                'slug' => 'enduro-matic-s-(0,8-liter)',
                'price' => 50000,
                'sale_price' => 50000,
                'status' => Product::ACTIVE,
                'stock_status' => Product::STATUS_IN_STOCK,
                'manage_stock' => true,
                'publish_date' => now(),
                'excerpt' => '',
                'body' => '',
                'featured_image' => 'images/Enduro Matic S.jpg',
            ],
        ];

        // Menyimpan data produk
        foreach ($products as $productData) {
            $product = Product::create([
                'user_id' => $user->id,
                'sku' => $productData['sku'],
                'type' => Product::SIMPLE,
                'name' => $productData['name'],
                'slug' => $productData['slug'],
                'price' => $productData['price'],
                'sale_price' => $productData['sale_price'],
                'status' => $productData['status'],
                'stock_status' => $productData['stock_status'],
                'manage_stock' => $productData['manage_stock'],
                'publish_date' => $productData['publish_date'],
                'excerpt' => $productData['excerpt'],
                'body' => $productData['body'],
                'featured_image' => $productData['featured_image'],
            ]);

            // Menambahkan tag produk
            $randomTagIDs = Tag::all()->random(2)->pluck('id');
            $product->tags()->sync($randomTagIDs);

            // Menambahkan inventaris untuk produk
            ProductInventory::create([
                'product_id' => $product->id,
                'qty' => 100, // Jumlah stok
                'low_stock_threshold' => 10, // Ambang batas stok rendah
            ]);
        }

        $this->command->info('33 Sample products seeded.');
    }
}
